---
title: "在R Markdown文档中使用中文"
author:
  - 秦佳玥
documentclass: ctexart
keywords:
  - 中文
  - R Markdown
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

```{r}
# 安装和加载必要的包
install.packages("ggplot2")  # 如果尚未安装ggplot2包，请先安装
library(ggplot2)
```



```{r}
result_lightgbm <- read.csv("result_lightGBM.csv")
result_rf <- read.csv("result_rf.csv")
result_catboost <- read.csv("result_catboost.csv")
result_svm <- read.csv("result_svm_10itrations0608.csv")
result_xgboost<- read.csv("result_xgboost_10itrations0607.csv")
```

```{r}

# 合并数据框
data <- data.frame(
  Model = rep(c("lightGBM", "rf", "catboost", "svm", "xgboost"), each = 10),
  log_loss_train = c(result_lightgbm$best_value_lightGBM, result_rf$best_value_rf, result_catboost$best_value_catboost, result_svm$best_value, result_xgboost$best_value)
)

# 绘制箱线图
ggplot(data, aes(x = Model, y = log_loss_train)) +
  geom_boxplot( outlier.shape = 16, width = 0.5) +
  labs(x = "Model", y = "Balenced Log Loss") +
  ggtitle("Balenced Log Loss for 5 Models") +
  theme(plot.title = element_text(hjust = 0.5))


```

```{r}
# 合并数据框
data <- data.frame(
  Model = rep(c("lightGBM", "rf", "catboost", "svm", "xgboost"), each = 10),
  time = c(result_lightgbm$time_comsumed, result_rf$time_comsumed_rf, result_catboost$time_comsumed_catboost, result_svm$time_comsumed, result_xgboost$time_comsumed)
)

# 绘制箱线图
ggplot(data, aes(x = Model, y = time)) +
  geom_boxplot( outlier.shape = 16, width = 0.5) +
  labs(x = "Model", y = "Time") +
  ggtitle("Time for 5 Models") +
  theme(plot.title = element_text(hjust = 0.5))
```






